dataloader:
  train:
    batch_size: 1
    shuffle: True
    num_workers: 2
  validation:
    batch_size: 1
    shuffle: False
    num_workers: 2
  test:
    batch_size: 1
    shuffle: False
    num_workers: 2
